/**
 * SCAPE REST API
 * SCAPE REST API for Authentication, User and Group Management
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ResultsMeta {
    /**
     * The actual number of returned items.
     */
    count?: number;

    /**
     * The total size of the collection of results.
     */
    total?: number;

    /**
     * Сorresponds to the requested limit parameter.
     */
    limit?: number;

    /**
     * Сorresponds to the requested offset parameter.
     */
    offset?: number;

}
